### PR TITLE
Rename Servo.h to ESP32ArduinoServo.h

### LINKED ISSUE #9: Naming conflicts with "default" <Servo.h>
When compiling for the `DOIT ESP32 DEVKIT V1` board on Arduino IDE `1.8.10` I am getting conflicts with the "default" Arduino servo library.

Due to this problem, none of the **examples** compiles.

This is easily fixed by changing the name of the header file to something more unique. Ideally, Arduino IDE would have a way of differentiating them, but yeah, it doesn't.

I suggest by renaming `Servo.h` :arrow_right: `ESP32ArduinoServo.h`. Based on the name you have chosen for your repository, this sounds like a reasonable choice to me. 

#10 should solve this issue.

### PR DESCRIPTION
**Pull request by platisd**
This will help the library avoid naming clashes with the default Arduino servo library.

Fixes #9

### CODE REVIEW

**Comment by ruiseixasm** [comment]
Still gives all these errors. This should have be done from the beginning by the author!

Arduino: 1.8.10 (Windows 10), Board: "DOIT ESP32 DEVKIT V1, 80MHz, 921600, None"

WARNING: library Servo claims to run on avr, megaavr, sam, samd, nrf52, stm32f4, mbed architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).
In file included from C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:33:0:

C:\Users\Utilizador\Documents\Arduino\libraries\Servo\src/Servo.h:77:2: error: #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

 #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

  ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:35:12: error: 'int Servo::channel_next_free' is not a static data member of 'class Servo'

 int Servo::channel_next_free = 0;

            ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp: In constructor 'Servo::Servo()':

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:38:18: error: '_resetFields' was not declared in this scope

     _resetFields();

                  ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp: At global scope:

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:41:15: error: definition of implicitly-declared 'Servo::~Servo()'

 Servo::~Servo() {

               ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:45:6: error: prototype for 'bool Servo::attach(int, int, int, int, int, int)' does not match any in class 'Servo'

 bool Servo::attach(int pin, int channel, 

      ^

In file included from C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:33:0:

C:\Users\Utilizador\Documents\Arduino\libraries\Servo\src/Servo.h:109:11: error: candidates are: uint8_t Servo::attach(int, int, int)

   uint8_t attach(int pin, int min, int max); // as above but also sets min and max values for writes. 

           ^

In file included from C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:33:0:

C:\Users\Utilizador\Documents\Arduino\libraries\Servo\src/Servo.h:108:11: error:                 uint8_t Servo::attach(int)

   uint8_t attach(int pin);           // attach the given pin to the next free channel, sets pinMode, returns channel number or 0 if failure

           ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:71:6: error: prototype for 'bool Servo::detach()' does not match any in class 'Servo'

 bool Servo::detach() {

      ^

In file included from C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:33:0:

C:\Users\Utilizador\Documents\Arduino\libraries\Servo\src/Servo.h:110:8: error: candidate is: void Servo::detach()

   void detach();

        ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp: In member function 'void Servo::write(int)':

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:84:34: error: '_minAngle' was not declared in this scope

     degrees = constrain(degrees, _minAngle, _maxAngle);

                                  ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:84:45: error: '_maxAngle' was not declared in this scope

     degrees = constrain(degrees, _minAngle, _maxAngle);

                                             ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:84:54: error: 'constrain' was not declared in this scope

     degrees = constrain(degrees, _minAngle, _maxAngle);

                                                      ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:85:41: error: '_angleToUs' was not declared in this scope

     writeMicroseconds(_angleToUs(degrees));

                                         ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp: In member function 'void Servo::writeMicroseconds(int)':

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:92:34: error: '_minPulseWidth' was not declared in this scope

     pulseUs = constrain(pulseUs, _minPulseWidth, _maxPulseWidth);

                                  ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:92:50: error: '_maxPulseWidth' was not declared in this scope

     pulseUs = constrain(pulseUs, _minPulseWidth, _maxPulseWidth);

                                                  ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:92:64: error: 'constrain' was not declared in this scope

     pulseUs = constrain(pulseUs, _minPulseWidth, _maxPulseWidth);

                                                                ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:93:5: error: '_pulseWidthDuty' was not declared in this scope

     _pulseWidthDuty = _usToDuty(pulseUs);

     ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:93:40: error: '_usToDuty' was not declared in this scope

     _pulseWidthDuty = _usToDuty(pulseUs);

                                        ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:94:15: error: '_channel' was not declared in this scope

     ledcWrite(_channel, _pulseWidthDuty);

               ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:94:40: error: 'ledcWrite' was not declared in this scope

     ledcWrite(_channel, _pulseWidthDuty);

                                        ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp: In member function 'int Servo::read()':

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:98:41: error: '_usToAngle' was not declared in this scope

     return _usToAngle(readMicroseconds());

                                         ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp: In member function 'int Servo::readMicroseconds()':

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:105:25: error: '_channel' was not declared in this scope

     int duty = ledcRead(_channel);

                         ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:105:33: error: 'ledcRead' was not declared in this scope

     int duty = ledcRead(_channel);

                                 ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:106:26: error: '_dutyToUs' was not declared in this scope

     return _dutyToUs(duty);

                          ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp: At global scope:

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:109:6: error: prototype for 'bool Servo::attached() const' does not match any in class 'Servo'

 bool Servo::attached() const { return _pin != PIN_NOT_ATTACHED; }

      ^

In file included from C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:33:0:

C:\Users\Utilizador\Documents\Arduino\libraries\Servo\src/Servo.h:115:8: error: candidate is: bool Servo::attached()

   bool attached();                   // return true if this servo is attached, otherwise false 

        ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:111:26: error: no 'int Servo::attachedPin() const' member function declared in class 'Servo'

 int Servo::attachedPin() const { return _pin; }

                          ^

C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master\src\ESP32ArduinoServo.cpp:113:30: error: no 'void Servo::_resetFields()' member function declared in class 'Servo'

 void Servo::_resetFields(void) {

                              ^

Multiple libraries were found for "ESP32ArduinoServo.h"
 Used: C:\Users\Utilizador\Documents\Arduino\libraries\ESP32-Arduino-Servo-Library-master
Multiple libraries were found for "Servo.h"
 Used: C:\Users\Utilizador\Documents\Arduino\libraries\Servo
 Not used: C:\Program
exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by JarekParal** [comment]
Hi, do you get this error in Arduino IDE? This library was created primarily for PlatformIO and there isn't such [warning](https://travis-ci.org/RoboticsBrno/ESP32-Arduino-Servo-Library/jobs/500296813?utm_medium=notification&utm_source=github_status).

**Comment by platisd** [comment]
> Hi, do you get this error in Arduino IDE? This library was created primarily for PlatformIO and there isn't such [warning](https://travis-ci.org/RoboticsBrno/ESP32-Arduino-Servo-Library/jobs/500296813?utm_medium=notification&utm_source=github_status).

Yes, Arduino IDE 1.8.10 running on Ubuntu 18.04 :+1:

**Comment by JarekParal** [comment]
Could you please post your program which created this error message? Also, I saw that in the log are Windows paths (e,g. `C:\Users\Utilizador\Documents\Arduino\libraries\Servo\src/Servo.h`). How you can then use Ubuntu?

**Comment by platisd** [comment]
> Could you please post your program which created this error message? Also, I saw that in the log are Windows paths (e,g. `C:\Users\Utilizador\Documents\Arduino\libraries\Servo\src/Servo.h`). How you can then use Ubuntu?

These are logs by @ruiseixasm who's probably using Windows, but I saw the pretty similar ones on my system. You can easily reproduce them by [downloading the Arduino IDE](https://www.arduino.cc/en/Main/Software), then installing the library, installing the ESP32 boards and finally trying to compile one of the examples.

**Comment by platisd** [comment]
This is no longer needed as per Arduino IDE 1.8.11

**Pull request closed without merging**
